export const emoticons = [
  { title: ":1:", src: "./emoticon/1.gif" },
  { title: ":2:", src: "./emoticon/2.gif" },
  { title: ":3:", src: "./emoticon/3.gif" },
  { title: ":4:", src: "./emoticon/4.gif" },
  { title: ":5:", src: "./emoticon/5.gif" },
  { title: ":6:", src: "./emoticon/6.gif" },
  { title: ":7:", src: "./emoticon/7.gif" },
  { title: ":8:", src: "./emoticon/8.gif" },
  { title: ":9:", src: "./emoticon/9.gif" },
  { title: ":10:", src: "./emoticon/10.gif" },
  { title: ":11:", src: "./emoticon/11.gif" },
  { title: ":12:", src: "./emoticon/12.gif" },
  { title: ":13:", src: "./emoticon/13.gif" },
  { title: ":14:", src: "./emoticon/14.gif" },
  { title: ":15:", src: "./emoticon/15.gif" },
  { title: ":16:", src: "./emoticon/16.gif" },
  { title: ":17:", src: "./emoticon/17.gif" },
  { title: ":18:", src: "./emoticon/18.gif" },
  { title: ":19:", src: "./emoticon/19.gif" },
  { title: ":20:", src: "./emoticon/20.gif" },
  { title: ":21:", src: "./emoticon/21.gif" },
  { title: ":22:", src: "./emoticon/22.gif" },
  { title: ":23:", src: "./emoticon/23.gif" },
  { title: ":24:", src: "./emoticon/24.gif" },
  { title: ":25:", src: "./emoticon/25.gif" },
  { title: ":26:", src: "./emoticon/26.gif" },
  { title: ":27:", src: "./emoticon/27.gif" },
  { title: ":28:", src: "./emoticon/28.gif" },
  { title: ":29:", src: "./emoticon/29.gif" },
  { title: ":30:", src: "./emoticon/30.gif" },
  { title: ":31:", src: "./emoticon/31.gif" },
  { title: ":32:", src: "./emoticon/32.gif" },
  { title: ":33:", src: "./emoticon/33.gif" },
  { title: ":34:", src: "./emoticon/34.gif" },
  { title: ":35:", src: "./emoticon/35.gif" },
  { title: ":36:", src: "./emoticon/36.gif" },
  { title: ":37:", src: "./emoticon/37.gif" },
  { title: ":38:", src: "./emoticon/38.gif" },
  { title: ":39:", src: "./emoticon/39.gif" },
  { title: ":40:", src: "./emoticon/40.gif" },
  { title: ":41:", src: "./emoticon/41.gif" },
  { title: ":42:", src: "./emoticon/42.gif" },
  { title: ":43:", src: "./emoticon/43.gif" },
  { title: ":44:", src: "./emoticon/44.gif" },
  { title: ":45:", src: "./emoticon/45.gif" },
];

export const emoticonsMap = {
  ":1:": "./emoticon/1.gif",
  ":2:": "./emoticon/2.gif",
  ":3:": "./emoticon/3.gif",
  ":4:": "./emoticon/4.gif",
  ":5:": "./emoticon/5.gif",
  ":6:": "./emoticon/6.gif",
  ":7:": "./emoticon/7.gif",
  ":8:": "./emoticon/8.gif",
  ":9:": "./emoticon/9.gif",
  ":10:": "./emoticon/10.gif",
  ":11:": "./emoticon/11.gif",
  ":12:": "./emoticon/12.gif",
  ":13:": "./emoticon/13.gif",
  ":14:": "./emoticon/14.gif",
  ":15:": "./emoticon/15.gif",
  ":16:": "./emoticon/16.gif",
  ":17:": "./emoticon/17.gif",
  ":18:": "./emoticon/18.gif",
  ":19:": "./emoticon/19.gif",
  ":20:": "./emoticon/20.gif",
  ":21:": "./emoticon/21.gif",
  ":22:": "./emoticon/22.gif",
  ":23:": "./emoticon/23.gif",
  ":24:": "./emoticon/24.gif",
  ":25:": "./emoticon/25.gif",
  ":26:": "./emoticon/26.gif",
  ":27:": "./emoticon/27.gif",
  ":28:": "./emoticon/28.gif",
  ":29:": "./emoticon/29.gif",
  ":30:": "./emoticon/30.gif",
  ":31:": "./emoticon/31.gif",
  ":32:": "./emoticon/32.gif",
  ":33:": "./emoticon/33.gif",
  ":34:": "./emoticon/34.gif",
  ":35:": "./emoticon/35.gif",
  ":36:": "./emoticon/36.gif",
  ":37:": "./emoticon/37.gif",
  ":38:": "./emoticon/38.gif",
  ":39:": "./emoticon/39.gif",
  ":40:": "./emoticon/40.gif",
  ":41:": "./emoticon/41.gif",
  ":42:": "./emoticon/42.gif",
  ":43:": "./emoticon/43.gif",
  ":44:": "./emoticon/44.gif",
  ":45:": "./emoticon/45.gif",
};
