/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   emoticons.ts                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: afarachi <afarachi@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/06/22 15:15:16 by afarachi          #+#    #+#             */
/*   Updated: 2025/06/22 15:15:16 by afarachi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

export const emojis = [
  { title: ":nerd:" , src: "./emojis/28021-nerd.gif" },
  { title: ":cool:" , src: "./emojis/28433-cool.gif" },
  { title: ":hearteyes:" , src: "./emojis/29364-hearteyes.gif" },
  { title: ":hot:" , src: "./emojis/30949-hot.gif" },
  { title: ":cold:" , src: "./emojis/40051-cold.gif" },
  { title: ":laugh:" , src: "./emojis/44214-laugh.gif" },
  { title: ":think:" , src: "./emojis/46858-think.gif" },
  { title: ":anxious:" , src: "./emojis/49113-anxious.gif" },
  { title: ":freaky:" , src: "./emojis/49250-freaky-1.gif" },
  { title: ":inlove:" , src: "./emojis/61731-inlove.gif" },
  { title: ":beg:" , src: "./emojis/62056-beg.gif" },
  { title: ":nervous:" , src: "./emojis/67648-nervous.gif" },
  { title: ":mindblown:" , src: "./emojis/69855-mindblown.gif" },
  { title: ":curious:" , src: "./emojis/77608-curious.gif" },
  { title: ":silent:" , src: "./emojis/81026-silent.gif" },
  { title: ":sleep:" , src: "./emojis/83447-sleep.gif" },
  { title: ":sob:" , src: "./emojis/85136-sob.gif" },
  { title: ":eyeroll:" , src: "./emojis/92946-eyeroll.gif" },
  { title: ":money:" , src: "./emojis/95835-money.gif" },
  { title: ":starstruck:" , src: "./emojis/96566-starstruck.gif" },
  { title: ":breathe:" , src: "./emojis/27364-breathe.gif" },
  { title: ":wink:" , src: "./emojis/25729-wink.gif" },
  { title: ":angry:" , src: "./emojis/21493-angry.gif" },
  { title: ":gasp:" , src: "./emojis/20543-gasp.gif" },
  { title: ":yawn:" , src: "./emojis/17320-yawn.gif" },
  { title: ":party:" , src: "./emojis/13961-party.gif" },
  { title: ":flustered:" , src: "./emojis/11975-flustered.gif" },
  { title: ":smirk:" , src: "./emojis/11438-smirk.gif" },
  { title: ":shy:" , src: "./emojis/7091-shy.gif" },
  { title: ":crazy:" , src: "./emojis/2587-crazy.gif" },
  { title: ":yum:" , src: "./emojis/1352-yum.gif" },
];

export const emojisMap = {
  ":nerd:": "./emojis/28021-nerd.gif",
  ":cool:": "./emojis/28433-cool.gif",
  ":hearteyes:": "./emojis/29364-hearteyes.gif",
  ":hot:": "./emojis/30949-hot.gif",
  ":cold:": "./emojis/40051-cold.gif",
  ":laugh:": "./emojis/44214-laugh.gif",
  ":think:": "./emojis/46858-think.gif",
  ":anxious:": "./emojis/49113-anxious.gif",
  ":freaky:": "./emojis/49250-freaky-1.gif",
  ":inlove:": "./emojis/61731-inlove.gif",
  ":beg:": "./emojis/62056-beg.gif",
  ":nervous:": "./emojis/67648-nervous.gif",
  ":mindblown:": "./emojis/69855-mindblown.gif",
  ":curious:": "./emojis/77608-curious.gif",
  ":silent:": "./emojis/81026-silent.gif",
  ":sleep:": "./emojis/83447-sleep.gif",
  ":sob:": "./emojis/85136-sob.gif",
  ":eyeroll:": "./emojis/92946-eyeroll.gif",
  ":money:": "./emojis/95835-money.gif",
  ":starstruck:": "./emojis/96566-starstruck.gif",
  ":breathe:": "./emojis/27364-breathe.gif",
  ":wink:": "./emojis/25729-wink.gif",
  ":angry:": "./emojis/21493-angry.gif",
  ":gasp:": "./emojis/20543-gasp.gif",
  ":yawn:": "./emojis/17320-yawn.gif",
  ":party:": "./emojis/13961-party.gif",
  ":flustered:": "./emojis/11975-flustered.gif",
  ":smirk:": "./emojis/11438-smirk.gif",
  ":shy:": "./emojis/7091-shy.gif",
  ":crazy:": "./emojis/2587-crazy.gif",
  ":yum:": "./emojis/1352-yum.gif",
};

export const emoticons = [
  { title: ":1:", src: "./emoticon/1.gif" },
  { title: ":2:", src: "./emoticon/2.gif" },
  { title: ":3:", src: "./emoticon/3.gif" },
  { title: ":4:", src: "./emoticon/4.gif" },
  { title: ":5:", src: "./emoticon/5.gif" },
  { title: ":6:", src: "./emoticon/6.gif" },
  { title: ":7:", src: "./emoticon/7.gif" },
  { title: ":8:", src: "./emoticon/8.gif" },
  { title: ":9:", src: "./emoticon/9.gif" },
  { title: ":10:", src: "./emoticon/10.gif" },
  { title: ":11:", src: "./emoticon/11.gif" },
  { title: ":12:", src: "./emoticon/12.gif" },
  { title: ":13:", src: "./emoticon/13.gif" },
  { title: ":14:", src: "./emoticon/14.gif" },
  { title: ":15:", src: "./emoticon/15.gif" },
  { title: ":16:", src: "./emoticon/16.gif" },
  { title: ":17:", src: "./emoticon/17.gif" },
  { title: ":18:", src: "./emoticon/18.gif" },
  { title: ":19:", src: "./emoticon/19.gif" },
  { title: ":20:", src: "./emoticon/20.gif" },
  { title: ":21:", src: "./emoticon/21.gif" },
  { title: ":22:", src: "./emoticon/22.gif" },
  { title: ":23:", src: "./emoticon/23.gif" },
  { title: ":24:", src: "./emoticon/24.gif" },
  { title: ":25:", src: "./emoticon/25.gif" },
  { title: ":26:", src: "./emoticon/26.gif" },
  { title: ":27:", src: "./emoticon/27.gif" },
  { title: ":28:", src: "./emoticon/28.gif" },
  { title: ":29:", src: "./emoticon/29.gif" },
  { title: ":30:", src: "./emoticon/30.gif" },
  { title: ":31:", src: "./emoticon/31.gif" },
  { title: ":32:", src: "./emoticon/32.gif" },
  { title: ":33:", src: "./emoticon/33.gif" },
  { title: ":34:", src: "./emoticon/34.gif" },
  { title: ":35:", src: "./emoticon/35.gif" },
  { title: ":36:", src: "./emoticon/36.gif" },
  { title: ":37:", src: "./emoticon/37.gif" },
  { title: ":38:", src: "./emoticon/38.gif" },
  { title: ":39:", src: "./emoticon/39.gif" },
  { title: ":40:", src: "./emoticon/40.gif" },
  { title: ":41:", src: "./emoticon/41.gif" },
  { title: ":42:", src: "./emoticon/42.gif" },
  { title: ":43:", src: "./emoticon/43.gif" },
  { title: ":44:", src: "./emoticon/44.gif" },
  { title: ":45:", src: "./emoticon/45.gif" },
  { title: ":46:", src: "./emoticon/46.gif" },
  { title: ":47:", src: "./emoticon/47.gif" },
  { title: ":48:", src: "./emoticon/48.gif" },
  { title: ":49:", src: "./emoticon/49.gif" },
];

export const emoticonsMap = {
  ":1:": "./emoticon/1.gif",
  ":2:": "./emoticon/2.gif",
  ":3:": "./emoticon/3.gif",
  ":4:": "./emoticon/4.gif",
  ":5:": "./emoticon/5.gif",
  ":6:": "./emoticon/6.gif",
  ":7:": "./emoticon/7.gif",
  ":8:": "./emoticon/8.gif",
  ":9:": "./emoticon/9.gif",
  ":10:": "./emoticon/10.gif",
  ":11:": "./emoticon/11.gif",
  ":12:": "./emoticon/12.gif",
  ":13:": "./emoticon/13.gif",
  ":14:": "./emoticon/14.gif",
  ":15:": "./emoticon/15.gif",
  ":16:": "./emoticon/16.gif",
  ":17:": "./emoticon/17.gif",
  ":18:": "./emoticon/18.gif",
  ":19:": "./emoticon/19.gif",
  ":20:": "./emoticon/20.gif",
  ":21:": "./emoticon/21.gif",
  ":22:": "./emoticon/22.gif",
  ":23:": "./emoticon/23.gif",
  ":24:": "./emoticon/24.gif",
  ":25:": "./emoticon/25.gif",
  ":26:": "./emoticon/26.gif",
  ":27:": "./emoticon/27.gif",
  ":28:": "./emoticon/28.gif",
  ":29:": "./emoticon/29.gif",
  ":30:": "./emoticon/30.gif",
  ":31:": "./emoticon/31.gif",
  ":32:": "./emoticon/32.gif",
  ":33:": "./emoticon/33.gif",
  ":34:": "./emoticon/34.gif",
  ":35:": "./emoticon/35.gif",
  ":36:": "./emoticon/36.gif",
  ":37:": "./emoticon/37.gif",
  ":38:": "./emoticon/38.gif",
  ":39:": "./emoticon/39.gif",
  ":40:": "./emoticon/40.gif",
  ":41:": "./emoticon/41.gif",
  ":42:": "./emoticon/42.gif",
  ":43:": "./emoticon/43.gif",
  ":44:": "./emoticon/44.gif",
  ":45:": "./emoticon/45.gif",
  ":46:": "./emoticon/46.gif",
  ":47:": "./emoticon/47.gif",
  ":48:": "./emoticon/48.gif",
  ":49:": "./emoticon/49.gif",
};

export const stickers = [
  { title: ":466:" , src: "./stickers/466.gif" },
  { title: ":477:" , src: "./stickers/477.gif" },
  { title: ":488:" , src: "./stickers/488.gif" },
  { title: ":499:" , src: "./stickers/499.gif" },
  { title: ":50:" , src: "./stickers/50.gif" },
  { title: ":51:" , src: "./stickers/51.gif" },
  { title: ":52:" , src: "./stickers/52.gif" },
  { title: ":53:" , src: "./stickers/53.gif" },
  { title: ":54:" , src: "./stickers/54.gif" },
  { title: ":55:" , src: "./stickers/55.gif" },
  { title: ":56:" , src: "./stickers/56.gif" },
  { title: ":57:" , src: "./stickers/57.gif" },
  { title: ":58:" , src: "./stickers/58.gif" },
  { title: ":59:" , src: "./stickers/59.gif" },
  { title: ":60:" , src: "./stickers/60.gif" },
  { title: ":61:" , src: "./stickers/61.gif" },
  { title: ":62:" , src: "./stickers/62.gif" },
  { title: ":63:" , src: "./stickers/63.gif" },
  { title: ":64:" , src: "./stickers/64.gif" },
  { title: ":65:" , src: "./stickers/65.gif" },
  { title: ":66:" , src: "./stickers/66.gif" },
  { title: ":67:" , src: "./stickers/67.gif" },
  { title: ":68:" , src: "./stickers/68.gif" },
  { title: ":69:" , src: "./stickers/69.gif" },
  { title: ":70:" , src: "./stickers/70.gif" },
  { title: ":71:" , src: "./stickers/71.gif" },
  { title: ":72:" , src: "./stickers/72.gif" },
  { title: ":73:" , src: "./stickers/73.gif" },
  { title: ":74:" , src: "./stickers/74.gif" },
  { title: ":75:" , src: "./stickers/75.gif" },
  { title: ":76:" , src: "./stickers/76.gif" },
  { title: ":77:" , src: "./stickers/77.gif" },
  { title: ":78:" , src: "./stickers/78.gif" },
];

export const stickersMap = {
  ":466:": "./stickers/466.gif",
  ":477:": "./stickers/477.gif",
  ":488:": "./stickers/488.gif",
  ":499:": "./stickers/499.gif",
  ":50:": "./stickers/50.gif",
  ":51:": "./stickers/51.gif",
  ":52:": "./stickers/52.gif",
  ":53:": "./stickers/53.gif",
  ":54:": "./stickers/54.gif",
  ":55:": "./stickers/55.gif",
  ":56:": "./stickers/56.gif",
  ":57:": "./stickers/57.gif",
  ":58:": "./stickers/58.gif",
  ":59:": "./stickers/59.gif",
  ":60:": "./stickers/60.gif",
  ":61:": "./stickers/61.gif",
  ":62:": "./stickers/62.gif",
  ":63:": "./stickers/63.gif",
  ":64:": "./stickers/64.gif",
  ":65:": "./stickers/65.gif",
  ":66:": "./stickers/66.gif",
  ":67:": "./stickers/67.gif",
  ":68:": "./stickers/68.gif",
  ":69:": "./stickers/69.gif",
  ":70:": "./stickers/70.gif",
  ":71:": "./stickers/71.gif",
  ":72:": "./stickers/72.gif",
  ":73:": "./stickers/73.gif",
  ":74:": "./stickers/74.gif",
  ":75:": "./stickers/75.gif",
  ":76:": "./stickers/76.gif",
  ":77:": "./stickers/77.gif",
  ":78:": "./stickers/78.gif",
};
